name: Publish to RubyGems

on:
  release:
    types:
      - [ created ]
  push:
    tags:
      - "v*"

jobs: 
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      TARGET_URL: https://rubygems.org/gems/faker

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Build Gem
        run: gem build -o faker.gem faker.gemspec

      - name: Push to RubyGems
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
        run: gem push faker.gem
